name: TestEnv

on:
  push:
    branches:
      - master
      - test
  pull_request:
  workflow_dispatch:
    inputs:
      all:
        type: boolean
        description: Build for all environments
      environment:
        type: environment
        description: Env

jobs:
  test:
    name: Run ${{ matrix.environment }}
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ ((github.event.event_name != 'workflow_dispatch' || github.event.inputs.all) && fromJson('["qa", "production"]')) || github.event.inputs.environment && fromJson(format('["{0}"]',  github.event.inputs.environment)) }}
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    environment:
      name: ${{ matrix.environment }}
      url: ${{ steps.build.outputs.url_output }}
    steps:
      - id: build
        run: |
          echo ${{ vars.SLACK_CHANNEL }}
          if [[ "${{ matrix.environment }}" == "production" ]]; then
            echo "url_output=https://google.com" >> $GITHUB_OUTPUT
          else
            echo "url_output=https://github.com" >> $GITHUB_OUTPUT
          fi
