name: TestEnv

on:
  push:
    branches:
      - master
      - test
  pull_request:
  workflow_dispatch:
    inputs:
      all:
        type: boolean
        description: Build for all environments
      environment:
        type: environment
        description: Env

jobs:
  test:
    name: Run ${{ matrix.environment }}
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ ((github.event.event_name != 'workflow_dispatch' || github.event.inputs.all) && fromJson('["qa", "production"]')) || github.event.inputs.environment && fromJson(format('["{0}"]',  github.event.inputs.environment)) }}
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    environment: ${{ matrix.environment }}
    steps:
      - run: echo ${{ vars.SLACK_CHANNEL }}
      # - name: Checkout code
      #   uses: actions/checkout@v2
